### ISSUE TITLE
登壇者 Yaml ファイルに 登壇資料の URL を追加

### ISSUE THREAD

**Issue by mikakane** [kfug/frontconf2018#36]
#frontkansai ハッシュタグより追ってください。
Issue 概要部分に一覧掲載し、誰のが集まってるか Issue で分かるように整えてください。

**Comment by iLLviA** [comment]
尾上洋介
榊原昌彦
カイト
中津川篤司
深沢幸治郎
宇都宮佑亮
コンチ
okunokentaro
Wakai Shinichiro
上原晃人
後藤知宏
yasui risa
